name: Validate .NET code samples
on: push
jobs:
  validate-dotnet:
    name: Validate .NET project
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    strategy:
      matrix:
        project-directory:
          - ./101-client-connection-string
          - ./102-client-default-credential
          - ./104-client-secret-credential
          - ./200-create-table
          - ./250-create-row
    defaults:
      run:
        working-directory: ${{ matrix.project-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3       
      - name: Build .NET project
        run: dotnet build
      - name: Check .NET code format
        run: dotnet format --verify-no-changes